name: IgnoreChat
main: com.github.Heliwr.IgnoreChat.Ignore
version: 1.4
author: feildmaster, Heliwr
softdepend: [CommandBook]
commands:
  ignore:
    description: Ignore a player or group
  ignore-list:
    description: List ignored players
permissions:
  ignore.use:
    default: true
  ignore.block:
    default: op