name: IgnoreChat
main: com.github.Heliwr.IgnoreChat.Ignore
version: 1.4.4
author: feildmaster, Heliwr
softdepend: [CommandBook]
commands:
  ignore:
    description: Ignore a player or group
  ignore-list:
    description: List ignored players
  socialspy:
    description: Listen in on private messages
permissions:
  ignore.use:
    default: true
  ignore.block:
    default: op
  ignore.socialspy:
    default: op