name: IgnoreChat
main: com.github.Heliwr.IgnoreChat.IgnoreChat
version: 1.2
author: feildmaster, Heliwr
commands:
  ignore:
    description: Ignore a player or group
  ignore-list:
    description: List ignored players
permissions:
  ignore.use:
    default: true
  ignore.block:
    default: op